/* Marketing compositions: the same canvas powers preview and PNG export. */
let marketing={name:'',details:'',brand:'',goal:'Giới thiệu',offer:'',image:'',aspect:'4:5',selected:'launch',copies:null,cutout:'',job:null};
try{Object.assign(marketing,JSON.parse(localStorage.getItem('mivy-marketing-v1')||'{}'))}catch{}
const marketingNames={launch:'01 · Ra mắt nổi bật',story:'02 · Kể câu chuyện',action:'03 · Thúc đẩy hành động'};
function saveMarketing(){try{localStorage.setItem('mivy-marketing-v1',JSON.stringify(marketing))}catch{toast('Bộ nhớ đã đầy. Anh tải bộ kết quả để giữ lại nhé.')}}
function marketingStudio(){screen='marketing';shell('Tạo quảng cáo',`<div class="simple-heading"><div><h1>Một ý tưởng. Ba mẫu quảng cáo.</h1><p class="muted">Thêm ảnh và mô tả ngắn. Chọn mẫu, sửa chữ, tải về.</p></div></div>
<form id="marketing-form" class="card marketing-brief"><div class="marketing-upload"><label for="marketing-file" class="secondary">${marketing.image?'Đổi ảnh':'＋ Thêm ảnh'}</label><input id="marketing-file" type="file" accept="image/png,image/jpeg,image/webp" hidden>${marketing.image?`<img src="${esc(marketing.image)}" alt="Ảnh của anh">`:'<p class="hint">Ảnh sản phẩm, dịch vụ hoặc sự kiện · tối đa 2 MB</p>'}</div><div class="marketing-fields"><label>Anh muốn quảng bá gì?<input name="name" required maxlength="100" placeholder="Ví dụ: Bộ sưu tập giày mới" value="${esc(marketing.name)}"></label><label>Thông tin nổi bật<textarea name="details" required maxlength="1500" placeholder="Dành cho ai, có gì nổi bật?">${esc(marketing.details)}</textarea></label><div class="fields"><label>Mục tiêu<select name="goal">${['Giới thiệu','Ưu đãi','Đăng ký'].map(v=>`<option ${marketing.goal===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Tên thương hiệu<input name="brand" maxlength="50" value="${esc(marketing.brand)}" placeholder="Không bắt buộc"></label></div><label>Giá / ưu đãi / thời gian <span class="hint">· nếu có</span><input name="offer" maxlength="100" value="${esc(marketing.offer)}" placeholder="Chỉ nhập thông tin đã xác nhận"></label><button class="primary" type="submit">${marketing.copies?'Tạo lại 3 mẫu':'Tạo 3 mẫu quảng cáo'}</button></div></form><div id="marketing-results"></div>`);
 $('#marketing-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>2*1024*1024){toast('Anh chọn JPG/PNG/WEBP dưới 2 MB nhé.');return}readMarketing();uploadPending=true;const r=new FileReader();r.onload=()=>{uploadPending=false;marketing.image=r.result;marketing.cutout='';marketing.job=null;marketing.copies=null;saveMarketing();marketingStudio()};r.onerror=()=>{uploadPending=false;toast('Không đọc được ảnh.')};r.readAsDataURL(f)};
 $('#marketing-form').oninput=()=>{readMarketing();saveMarketing()};
 $('#marketing-form').onsubmit=async e=>{e.preventDefault();if(aiBusy||uploadPending)return;readMarketing();await buildMarketing()};
 if(marketing.copies)showMarketingResults();
}
function readMarketing(){const f=$('#marketing-form');if(f)for(const [k,v]of new FormData(f))marketing[k]=String(v).trim()}
async function buildMarketing(){setBusy(true);aiStatus('Đang viết ba hướng quảng cáo…');try{
 const copies=await api('/v1/creative/marketing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:marketing.name,details:marketing.details,brand:marketing.brand,goal:marketing.goal,offer:marketing.offer})});
 if(marketing.image&&!marketing.cutout){aiStatus('Đang chuẩn bị hình cho bố cục…');if(!marketing.job){const form=new FormData();form.append('background','studio_white');const blob=await(await fetch(marketing.image)).blob();form.append('image',blob,'source.'+(blob.type==='image/jpeg'?'jpg':blob.type==='image/webp'?'webp':'png'));marketing.job=(await api('/v1/creative/images',{method:'POST',body:form})).job_id;saveMarketing()}
 const start=Date.now();while(true){const j=await api('/v1/generations/'+marketing.job);if(j.status==='failed'){marketing.job=null;throw new Error(j.error)}if(j.status==='completed'){marketing.cutout='/v1/generations/'+marketing.job+'/cutout';marketing.job=null;break}if(Date.now()-start>650000)throw new Error('Ảnh vẫn đang xử lý. Anh bấm tạo lại để tiếp tục.');await new Promise(r=>setTimeout(r,1500))}}
 marketing.copies=copies;saveMarketing();marketingStudio();$('#marketing-results').scrollIntoView({behavior:'smooth'});toast('Đã tạo ba mẫu. Anh chọn mẫu để sửa và tải.');
 }catch(e){aiStatus(e.message,true)}finally{setBusy(false)}}
function showMarketingResults(){const c=marketing.copies[marketing.selected];$('#marketing-results').innerHTML=`<div class="section-top"><h2>Chọn hướng phù hợp</h2><label>Khổ ảnh<select id="marketing-aspect">${[['1:1','Vuông 1:1'],['4:5','Dọc 4:5'],['9:16','Story 9:16']].map(([k,v])=>`<option value="${k}" ${marketing.aspect===k?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="marketing-options">${Object.entries(marketingNames).map(([k,v])=>`<button class="marketing-option ${marketing.selected===k?'selected':''}" data-marketing-select="${k}"><canvas data-marketing-canvas="${k}"></canvas><b>${v}</b></button>`).join('')}</div><div class="card marketing-editor"><div><h2>${marketingNames[marketing.selected]}</h2>${[['headline','Tiêu đề',70],['subline','Thông điệp',140],['cta','Lời kêu gọi',40]].map(([k,v,n])=>`<label>${v}<input data-marketing-field="${k}" maxlength="${n}" value="${esc(c[k])}"></label>`).join('')}<button class="primary" id="marketing-download">↓ Tải mẫu đã chọn · PNG</button><button class="secondary" id="marketing-all">↓ Tải cả bộ · ZIP</button><p class="hint">Bộ ZIP gồm 3 ảnh PNG và caption tương ứng.</p></div><div><label>Caption đi kèm<textarea data-marketing-field="caption" rows="9">${esc(c.caption)}</textarea></label><button class="secondary" id="marketing-copy">Sao chép caption</button><button class="text-button" id="marketing-text">↓ Tải caption · TXT</button><p class="hint">Anh kiểm tra thông tin và ưu đãi trước khi đăng.</p></div></div>`;
 document.querySelectorAll('[data-marketing-select]').forEach(b=>b.onclick=()=>{marketing.selected=b.dataset.marketingSelect;saveMarketing();showMarketingResults()});
 $('#marketing-aspect').onchange=e=>{marketing.aspect=e.target.value;saveMarketing();paintMarketing()};
 document.querySelectorAll('[data-marketing-field]').forEach(el=>el.oninput=()=>{marketing.copies[marketing.selected][el.dataset.marketingField]=el.value;saveMarketing();paintMarketing()});
 $('#marketing-download').onclick=async()=>{try{await paintMarketing();const canvas=document.querySelector(`[data-marketing-canvas="${marketing.selected}"]`);canvas.toBlob(b=>{if(b)download(b,`mivy-${marketing.selected}-${marketing.aspect.replace(':','x')}.png`)})}catch(e){toast(e.message)}};
 $('#marketing-copy').onclick=async()=>{try{await navigator.clipboard.writeText(marketing.copies[marketing.selected].caption);toast('Đã sao chép caption.')}catch{toast('Anh chọn caption để sao chép nhé.')}};
 $('#marketing-text').onclick=()=>download(new Blob([Object.entries(marketing.copies).map(([k,v])=>marketingNames[k]+'\n'+v.caption).join('\n\n')],{type:'text/plain;charset=utf-8'}),'mivy-captions.txt');
 $('#marketing-all').onclick=async()=>{try{await paintMarketing();const files=[];for(const [k,v]of Object.entries(marketing.copies)){const canvas=document.querySelector(`[data-marketing-canvas="${k}"]`);const blob=await new Promise(r=>canvas.toBlob(r));files.push({name:k+'.png',data:new Uint8Array(await blob.arrayBuffer())},{name:k+'-caption.txt',data:new TextEncoder().encode(v.caption)})}download(marketingZip(files),'mivy-marketing.zip');toast('Đã tải bộ 3 ảnh và caption.')}catch(e){toast('Chưa tải được bộ ảnh. Anh thử lại nhé.')}};
 paintMarketing().catch(e=>toast(e.message));
}
let marketingImagePromise=null,marketingImageUrl='';
async function marketingAsset(){const url=marketing.cutout||marketing.image;if(!url)return null;if(url!==marketingImageUrl){marketingImageUrl=url;marketingImagePromise=(async()=>{const im=new Image();im.src=url;await im.decode();const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const x=c.getContext('2d');x.drawImage(im,0,0);const d=x.getImageData(0,0,c.width,c.height).data;let l=c.width,t=c.height,r=0,b=0;for(let y=0;y<c.height;y++)for(let z=0;z<c.width;z++)if(d[(y*c.width+z)*4+3]>8){l=Math.min(l,z);r=Math.max(r,z);t=Math.min(t,y);b=Math.max(b,y)}return {im,l,t,w:r-l+1,h:b-t+1}})()}return marketingImagePromise}
function posterText(ctx,text,x,y,width,maxHeight,start,color,weight='700'){let size=start,lines;do{ctx.font=`${weight} ${size}px Arial, sans-serif`;lines=[];let line='';for(const word of text.split(/\s+/)){const next=line?line+' '+word:word;if(ctx.measureText(next).width>width&&line){lines.push(line);line=word}else line=next}if(line)lines.push(line);if(lines.length*size*1.16<=maxHeight&&lines.every(l=>ctx.measureText(l).width<=width))break;size-=2}while(size>12);ctx.fillStyle=color;ctx.textBaseline='top';lines.forEach((l,i)=>ctx.fillText(l,x,y+i*size*1.16));return lines.length*size*1.16}
async function paintMarketing(){await document.fonts.ready;const asset=await marketingAsset();for(const canvas of document.querySelectorAll('[data-marketing-canvas]')){const k=canvas.dataset.marketingCanvas;drawMarketingPoster(canvas,k,marketing.copies[k],asset)}}
function drawMarketingPoster(canvas,kind,copy,asset){const w=1080,h={'1:1':1080,'4:5':1350,'9:16':1920}[marketing.aspect];canvas.width=w;canvas.height=h;const x=canvas.getContext('2d'),story=kind==='story',action=kind==='action';const bg=story?'#eee7da':action?'#e3edb9':'#162b28',fg=story?'#302b25':action?'#162b28':'#f2f5e9',accent=story?'#b96c48':'#d0f36d';x.fillStyle=bg;x.fillRect(0,0,w,h);const m=76;
 posterText(x,marketing.brand||marketing.name,m,55,850,55,26,fg);
 let imageBox;
 if(story){posterText(x,copy.headline,m,140,850,h*.22,78,fg);x.fillStyle='#d8c9b4';x.beginPath();x.ellipse(540,h*.54,430,h*.21,0,0,Math.PI*2);x.fill();imageBox=[95,h*.35,890,h*.35];posterText(x,copy.subline,m,h*.76,900,h*.1,35,fg,'400')}
 else if(action){x.fillStyle='#162b28';x.fillRect(0,h*.34,1080,h*.42);posterText(x,copy.headline,m,130,900,h*.19,88,fg);imageBox=[90,h*.38,900,h*.30];posterText(x,copy.subline,m,h*.78,900,h*.08,32,fg,'400')}
 else{posterText(x,copy.headline,m,145,900,h*.22,92,fg);x.save();x.translate(540,h*.55);x.rotate(-.15);x.fillStyle=accent;x.fillRect(-620,-h*.10,1240,h*.20);x.restore();imageBox=[80,h*.36,920,h*.34];posterText(x,copy.subline,m,h*.76,900,h*.09,34,fg,'400')}
 if(asset){const [bx,by,bw,bh]=imageBox;const scale=Math.min(bw/asset.w,bh/asset.h);x.save();x.shadowColor='#00000030';x.shadowBlur=30;x.shadowOffsetY=24;x.drawImage(asset.im,asset.l,asset.t,asset.w,asset.h,bx+(bw-asset.w*scale)/2,by+(bh-asset.h*scale)/2,asset.w*scale,asset.h*scale);x.restore()}
 else{posterText(x,marketing.name,110,h*.43,860,h*.22,90,action?'#e3edb9':fg)}
 if(marketing.offer)posterText(x,marketing.offer,m,h*.855,900,h*.045,28,fg);
 const cy=h-100;x.fillStyle=story?'#302b25':action?'#162b28':accent;x.fillRect(m,cy,928,64);posterText(x,copy.cta,m+25,cy+18,875,36,27,story?'#fff':action?'#fff':'#162b28');
}
