/* Marketing compositions: the same canvas powers preview and PNG export. */
let marketing={industry:'general',name:'',details:'',brand:'',goal:'Giới thiệu',offer:'',image:'',aspect:'4:5',selected:'launch',copies:null,cutout:'',job:null,theme:''};
try{Object.assign(marketing,JSON.parse(localStorage.getItem('mivy-marketing-v1')||'{}'))}catch{}
let marketingNames={launch:'01 · Ra mắt nổi bật',story:'02 · Kể câu chuyện',action:'03 · Thúc đẩy hành động'};
function saveMarketing(){try{localStorage.setItem('mivy-marketing-v1',JSON.stringify(marketing))}catch{toast('Bộ nhớ đã đầy. Anh tải bộ kết quả để giữ lại nhé.')}}
const industryConfig={
 general:{label:'Sản phẩm / Tự do',input:'Thông tin nổi bật',placeholder:'Dành cho ai, có gì nổi bật?',names:['Ra mắt nổi bật','Kể câu chuyện','Thúc đẩy hành động']},
 recruitment:{label:'Tuyển dụng',input:'Dán JD vào đây',placeholder:'Vị trí, yêu cầu, quyền lợi, địa điểm và cách ứng tuyển…',names:['Poster tuyển dụng','Ảnh phụ · Yêu cầu','Ảnh phụ · Liên hệ']},
 education:{label:'Khóa học',input:'Dán thông tin khóa học',placeholder:'Đối tượng học, nội dung, lịch học, học phí, cách đăng ký…',names:['Giới thiệu khóa học','Nội dung học','Thông tin đăng ký']},
 service:{label:'Dịch vụ',input:'Dán mô tả dịch vụ',placeholder:'Nhu cầu, hạng mục, gói giá, quy trình, cách đặt lịch…',names:['Giới thiệu dịch vụ','Hạng mục nổi bật','Liên hệ & đặt lịch']}
};
function marketingStudio(){const cfg=industryConfig[marketing.industry]||industryConfig.general;marketingNames=Object.fromEntries(['launch','story','action'].map((k,i)=>[k,`0${i+1} · ${cfg.names[i]}`]));screen='marketing';shell('Tạo quảng cáo',`<div class="simple-heading"><div><h1>${marketing.industry==='general'?'Một ý tưởng. Ba mẫu quảng cáo.':cfg.label+': nội dung dài, điểm nhấn rõ.'}</h1><p class="muted">Dán nội dung → chọn ý chính → tải bộ ảnh. Không bắt buộc có ảnh.</p></div></div>
<div class="industry-tabs" role="group" aria-label="Ngành nội dung">${Object.entries(industryConfig).map(([k,v])=>`<button class="${marketing.industry===k?'primary':'secondary'}" data-industry="${k}">${v.label}</button>`).join('')}</div><form id="marketing-form" class="card marketing-brief"><div class="marketing-upload">${marketing.image?'<div style="display:flex;gap:8px;justify-content:center"><label for="marketing-file" class="secondary">Đổi ảnh</label><button type="button" class="text-button" id="marketing-remove-img">Xóa ảnh</button></div>':'<label for="marketing-file" class="secondary">＋ Thêm ảnh</label>'}<input id="marketing-file" type="file" accept="image/png,image/jpeg,image/webp" hidden>${marketing.image?`<img src="${esc(marketing.image)}" alt="Ảnh của anh">`:'<p class="hint">Ảnh sản phẩm, dịch vụ hoặc sự kiện · tối đa 20 MB</p>'}</div><div class="marketing-fields"><label>Anh muốn quảng bá gì?<input name="name" required maxlength="100" placeholder="${marketing.industry==='recruitment'?'Ví dụ: Tuyển Frontend Developer':marketing.industry==='education'?'Ví dụ: Khóa giao tiếp tiếng Anh':marketing.industry==='service'?'Ví dụ: Thiết kế website':'Ví dụ: Bộ sưu tập giày mới'}" value="${esc(marketing.name)}"></label><label>${cfg.input}<textarea name="details" required maxlength="12000" rows="7" placeholder="${cfg.placeholder}">${esc(marketing.details)}</textarea></label><div class="fields"><label>Mục tiêu<select name="goal">${['Giới thiệu','Ưu đãi','Đăng ký','Ứng tuyển'].map(v=>`<option ${marketing.goal===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Tên thương hiệu<input name="brand" maxlength="50" value="${esc(marketing.brand)}" placeholder="Không bắt buộc"></label></div><label>${marketing.industry==='recruitment'?'Hạn ứng tuyển / ghi chú':marketing.industry==='education'?'Lịch học / học phí bổ sung':marketing.industry==='service'?'Gói giá / ghi chú':'Giá / ưu đãi / thời gian'} <span class="hint">· nếu có</span><input name="offer" maxlength="100" value="${esc(marketing.offer)}" placeholder="Chỉ nhập thông tin đã xác nhận"></label><button class="primary" type="submit">${marketing.copies?'Tạo lại 3 mẫu':'Tạo 3 mẫu quảng cáo'}</button></div></form><div id="marketing-results"></div>`);
 document.querySelectorAll('[data-industry]').forEach(b=>b.onclick=()=>{if(aiBusy)return;readMarketing();saveMarketing();try{localStorage.setItem('mivy-sector-'+marketing.industry,JSON.stringify(marketing))}catch{}const sector=b.dataset.industry;let saved={};try{saved=JSON.parse(localStorage.getItem('mivy-sector-'+sector)||'{}')}catch{}marketing={industry:sector,name:'',details:'',brand:'',goal:sector==='recruitment'?'Ứng tuyển':sector==='general'?'Giới thiệu':'Đăng ký',offer:'',image:'',aspect:'4:5',selected:'launch',copies:null,cutout:'',job:null,...saved};saveMarketing();marketingStudio()});
 $('#marketing-remove-img')?.addEventListener('click',()=>{marketing.image='';marketing.cutout='';marketing.job=null;saveMarketing();marketingStudio();paintMarketing();toast('Đã gỡ ảnh.')});
 $('#marketing-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>20*1024*1024){toast('Anh chọn JPG/PNG/WEBP dưới 20 MB nhé.');return}readMarketing();uploadPending=true;const r=new FileReader();r.onload=()=>{uploadPending=false;marketing.image=r.result;marketing.cutout='';marketing.job=null;marketing.copies=null;saveMarketing();marketingStudio()};r.onerror=()=>{uploadPending=false;toast('Không đọc được ảnh.')};r.readAsDataURL(f)};
 $('#marketing-form').oninput=()=>{readMarketing();saveMarketing()};
 $('#marketing-form').onsubmit=async e=>{e.preventDefault();if(aiBusy||uploadPending)return;readMarketing();await buildMarketing()};
 if(marketing.copies)showMarketingResults();
}
function readMarketing(){const f=$('#marketing-form');if(f)for(const [k,v]of new FormData(f))marketing[k]=String(v).trim()}
async function buildMarketing(){setBusy(true);aiStatus(marketing.industry==='general'?'Đang viết ba hướng quảng cáo…':'Đang chọn ý chính và soạn bộ 3 ảnh…');try{
 const copies=await api('/v1/creative/marketing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({industry:marketing.industry,name:marketing.name,details:marketing.details,brand:marketing.brand,goal:marketing.goal,offer:marketing.offer})});
  if(marketing.industry==='general'&&marketing.image&&!marketing.cutout){aiStatus('Đang chuẩn bị hình cho bố cục…');if(!marketing.job){const form=new FormData();form.append('background','studio_white');const blob=await(await fetch(marketing.image)).blob();form.append('image',blob,'source.'+(blob.type==='image/jpeg'?'jpg':blob.type==='image/webp'?'webp':'png'));marketing.job=(await api('/v1/creative/images',{method:'POST',body:form})).job_id;saveMarketing()}
  const start=Date.now();while(true){const j=await api('/v1/generations/'+marketing.job);if(j.status==='failed'){marketing.job=null;throw new Error(j.error)}if(j.status==='completed'){marketing.cutout='/v1/generations/'+marketing.job+'/cutout';marketing.job=null;break}if(Date.now()-start>650000)throw new Error('Ảnh vẫn đang xử lý. Anh bấm tạo lại để tiếp tục.');await new Promise(r=>setTimeout(r,1500))}}
  if(!marketing.image){aiStatus('Đang tạo ảnh nền Visual AI…');try{const bg=await api('/v1/creative/background',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({industry:marketing.industry,theme:marketing.theme||'emerald_pro',aspect_ratio:marketing.aspect||'4:5'})});if(bg&&bg.url)marketing.bgUrl=bg.url}catch(e){console.warn('Background AI fallback:',e)}}
  marketing.copies=copies;saveMarketing();marketingStudio();$('#marketing-results').scrollIntoView({behavior:'smooth'});toast('Đã tạo ba mẫu. Anh chọn mẫu để sửa và tải.');
  }catch(e){aiStatus(e.message,true)}finally{setBusy(false)}}
function showMarketingResults(){
 const c=marketing.copies[marketing.selected];
 const thList=Object.values(POSTER_THEMES);
 const curTh=getActiveTheme().id;
 $('#marketing-results').innerHTML=`<div class="section-top"><div><h2>${marketing.industry==='general'?'Chọn hướng phù hợp':marketing.industry==='recruitment'?'Poster chính & ảnh phụ':'Bộ 3 ảnh · mỗi ảnh một ý'}</h2><div class="theme-bar" role="group" aria-label="Giao diện poster"><span class="theme-lbl">Phong cách:</span>${thList.map(t=>`<button type="button" class="theme-chip ${curTh===t.id?'active':''}" data-poster-theme="${t.id}">${t.name}</button>`).join('')}<button type="button" class="theme-chip" id="marketing-refresh-bg" title="Tạo ảnh nền Visual AI mới">✨ Đổi nền AI</button></div></div><label>Khổ ảnh<select id="marketing-aspect">${[['1:1','Vuông 1:1'],['4:5','Dọc 4:5'],['9:16','Story 9:16']].map(([k,v])=>`<option value="${k}" ${marketing.aspect===k?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="marketing-options ${marketing.industry==='recruitment'?'recruitment-options':''}">${Object.entries(marketingNames).map(([k,v])=>`<button class="marketing-option ${marketing.selected===k?'selected':''}" data-marketing-select="${k}"><canvas data-marketing-canvas="${k}"></canvas><b>${v}</b></button>`).join('')}</div><div class="card marketing-editor"><div><h2>${marketingNames[marketing.selected]}</h2>${[['headline','Tiêu đề',70],['subline','Thông điệp',140],['cta','Lời kêu gọi',40]].map(([k,v,n])=>`<label>${v}<input data-marketing-field="${k}" maxlength="${n}" value="${esc(c[k])}"></label>`).join('')}${marketing.industry!=='general'?`<label>Ý chính · mỗi dòng một ý, tối đa 10<textarea id="marketing-points" rows="3">${esc((c.points||[]).join('\n'))}</textarea></label>`:''}<button class="primary" id="marketing-download">↓ Tải mẫu đã chọn · PNG</button><button class="secondary" id="marketing-all">↓ Tải cả bộ · ZIP</button><p class="hint">Bộ ZIP gồm 3 ảnh PNG và caption tương ứng.</p></div><div><label>Caption đi kèm<textarea data-marketing-field="caption" rows="9">${esc(c.caption)}</textarea></label><button class="secondary" id="marketing-copy">Sao chép caption</button><button class="text-button" id="marketing-text">↓ Tải caption · TXT</button><p class="hint">Anh kiểm tra thông tin và ưu đãi trước khi đăng.</p></div></div>`;
 document.querySelectorAll('[data-marketing-select]').forEach(b=>b.onclick=()=>{marketing.selected=b.dataset.marketingSelect;saveMarketing();showMarketingResults()});
 document.querySelectorAll('[data-poster-theme]').forEach(b=>b.onclick=()=>{marketing.theme=b.dataset.posterTheme;saveMarketing();showMarketingResults();paintMarketing()});
 $('#marketing-refresh-bg')?.addEventListener('click',async()=>{aiStatus('Đang tạo ảnh nền Visual AI mới…');try{const res=await api('/v1/creative/background',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({industry:marketing.industry,theme:marketing.theme||'emerald_pro',aspect_ratio:marketing.aspect||'4:5',seed:Math.floor(Math.random()*999999)})});if(res&&res.url){marketing.bgUrl=res.url;marketingBgUrl='';saveMarketing();await paintMarketing();toast('Đã cập nhật nền Visual AI mới!')}}catch(e){toast('Chưa đổi được nền AI: '+e.message)}finally{aiStatus('')}});
 $('#marketing-points')?.addEventListener('input',e=>{marketing.copies[marketing.selected].pointsEdited=true;marketing.copies[marketing.selected].points=e.target.value.split('\n').filter(Boolean).slice(0,10).map(v=>v.slice(0,180));saveMarketing();paintMarketing()});
 $('#marketing-aspect').onchange=e=>{marketing.aspect=e.target.value;saveMarketing();paintMarketing()};
 document.querySelectorAll('[data-marketing-field]').forEach(el=>el.oninput=()=>{marketing.copies[marketing.selected][el.dataset.marketingField]=el.value;saveMarketing();paintMarketing()});
 $('#marketing-download').onclick=async()=>{try{await paintMarketing();const canvas=document.querySelector(`[data-marketing-canvas="${marketing.selected}"]`);canvas.toBlob(b=>{if(b)download(b,`mivy-${marketing.selected}-${marketing.aspect.replace(':','x')}.png`)})}catch(e){toast(e.message)}};
 $('#marketing-copy').onclick=async()=>{try{await navigator.clipboard.writeText(marketing.copies[marketing.selected].caption);toast('Đã sao chép caption.')}catch{toast('Anh chọn caption để sao chép nhé.')}};
 $('#marketing-text').onclick=()=>download(new Blob([Object.entries(marketing.copies).map(([k,v])=>marketingNames[k]+'\n'+v.caption).join('\n\n')],{type:'text/plain;charset=utf-8'}),'mivy-captions.txt');
 $('#marketing-all').onclick=async()=>{try{await paintMarketing();const files=[];for(const [k,v]of Object.entries(marketing.copies)){const canvas=document.querySelector(`[data-marketing-canvas="${k}"]`);const blob=await new Promise(r=>canvas.toBlob(r));files.push({name:k+'.png',data:new Uint8Array(await blob.arrayBuffer())},{name:k+'-caption.txt',data:new TextEncoder().encode(v.caption)})}files.push({name:'noi-dung-goc.txt',data:new TextEncoder().encode(marketing.name+'\n'+marketing.details+'\n'+marketing.offer)});download(marketingZip(files),'mivy-marketing.zip');toast('Đã tải bộ 3 ảnh và caption.')}catch(e){toast('Chưa tải được bộ ảnh. Anh thử lại nhé.')}};
 paintMarketing().catch(e=>toast(e.message));
}
let marketingImagePromise=null,marketingImageUrl='';
async function marketingAsset(){const url=marketing.cutout||marketing.image||'';if(!url)return null;if(url!==marketingImageUrl){marketingImageUrl=url;marketingImagePromise=(async()=>{const im=new Image();im.src=url;await im.decode();const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const x=c.getContext('2d');x.drawImage(im,0,0);const d=x.getImageData(0,0,c.width,c.height).data;let l=c.width,t=c.height,r=0,b=0;for(let y=0;y<c.height;y++)for(let z=0;z<c.width;z++)if(d[(y*c.width+z)*4+3]>8){l=Math.min(l,z);r=Math.max(r,z);t=Math.min(t,y);b=Math.max(b,y)}return {im,l,t,w:r-l+1,h:b-t+1}})()}return marketingImagePromise}
let marketingBgPromise=null,marketingBgUrl='';
async function marketingBg(){const url=marketing.bgUrl||'';if(!url)return null;if(url!==marketingBgUrl){marketingBgUrl=url;marketingBgPromise=(async()=>{try{const im=new Image();im.crossOrigin='anonymous';im.src=url;await im.decode();return im}catch(e){return null}})()}return marketingBgPromise}
function posterText(ctx,text,x,y,width,maxHeight,start,color,weight='700',family='Arial, sans-serif'){let size=start,lines;do{ctx.font=`${weight} ${size}px ${family}`;lines=[];let line='';for(const word of text.split(/\s+/)){const next=line?line+' '+word:word;if(ctx.measureText(next).width>width&&line){lines.push(line);line=word}else line=next}if(line)lines.push(line);if(lines.length*size*1.2<=maxHeight&&lines.every(l=>ctx.measureText(l).width<=width))break;size-=2}while(size>12);ctx.fillStyle=color;ctx.textBaseline='top';lines.forEach((l,i)=>ctx.fillText(l,x,y+i*size*1.2));return lines.length*size*1.2}
async function paintMarketing(){await document.fonts.ready;const [asset,bgImg]=await Promise.all([marketingAsset(),marketingBg()]);for(const canvas of document.querySelectorAll('[data-marketing-canvas]')){const k=canvas.dataset.marketingCanvas;drawMarketingPoster(canvas,k,marketing.copies[k],asset,bgImg)}}
function drawMarketingPoster(canvas,kind,copy,asset,bgImg){drawIndustryPoster(canvas,kind,copy,asset,bgImg)}
